### ISSUE TITLE
probing host network

### ISSUE THREAD

**Issue by basz** [instrumentisto/nmap-docker-image#1]
Being new to nmap and novisish in docker I have a question regarding the possibility of the following.

The goal is to scan a local network for attached devices. So I found nmap as that is supposed to be able to do that. Since this application will be running an a raspberry pi, managed via belena.com it will deploy docker containers.

However docker comes with it own networking stuff added on top of the host. My question is, can I use this docker image to scan the local network of the **host** to figure out connected devices...

thanks

**Comment by tyranron** [comment]
@basz yes, why not?

Just consider the [Docker networking model](https://docs.docker.com/network/), or use `--network=host` alltogether.

Rather than that this image is nothing more than just compiled `nmap` CLI tool with all its dependencies.

**Comment by basz** [comment]
Thx!

I've got it working indeed with the host option. Unfortunately that does not work on macOS.

**Comment by tyranron** [comment]
@basz because on macOS the Docker is emulated via virtual machine. macOS doesn't support Docker natively.
